FROM apache/airflow:2.9.3-python3.12

USER root

# Системные зависимости для kerberos/hdfs
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libkrb5-dev \
    krb5-config \
    libkrb5-3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Копируем requirements.txt
COPY --chown=airflow:airflow requirements.txt /tmp/requirements.txt

# Установка с официальными constraints Airflow 2.9.3
RUN pip install --no-cache-dir --default-timeout=300 --retries=10 \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.12.txt" \
    -r /tmp/requirements.txt

RUN pip cache purge 2>/dev/null || true